// Source code generated by AppGPT (www.appgpt.tech)

 //to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("NFLStars")
export class NFLStarsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
imageLink: string;


}
