// Source code generated by AppGPT (www.appgpt.tech)

 //Class to create tables and seed new database
import { DataSource } from "typeorm";
import { DBConfiguration } from "./Configuration";
import { SettingsEntity } from "./db/Settings.entity";
//autogenerate imports based on resources
import { PurchaseLinkEntity } from "./db/PurchaseLink.entity";
import { VideosEntity } from "./db/Videos.entity";
import { NFLStarsEntity } from "./db/NFLStars.entity";

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [SettingsEntity, PurchaseLinkEntity, VideosEntity, NFLStarsEntity];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables


    await Database.Seed();
  }
  static async Seed() {
    let data: any = {"PurchaseLink":[{"link":"link 1","id":42},{"link":"link 2","id":65},{"link":"link 3","id":78},{"link":"link 4","id":66},{"link":"link 5","id":57}],"Videos":[{"videoLink":"videoLink 1","id":95},{"videoLink":"videoLink 2","id":36},{"videoLink":"videoLink 3","id":99},{"videoLink":"videoLink 4","id":17},{"videoLink":"videoLink 5","id":14}],"NFLStars":[{"imageLink":"imageLink 1","id":49},{"imageLink":"imageLink 2","id":35},{"imageLink":"imageLink 3","id":77},{"imageLink":"imageLink 4","id":0},{"imageLink":"imageLink 5","id":13}]};
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true){
      console.log('   Seeding database...');
      await this.SeedResource("PurchaseLinkEntity", data.PurchaseLink);
await this.SeedResource("VideosEntity", data.Videos);
await this.SeedResource("NFLStarsEntity", data.NFLStars); 
      await this.SeedResource("SettingsEntity", {
        settingname: "isSeeded",
        settingvalue: "true",
      });
    }else{
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository("SettingsEntity");
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: "isSeeded",
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table '+resourceName);
    await repo.upsert(resourceData, ["id"]);
  }
}

