// Source code generated by AppGPT (www.appgpt.tech)

 
let data: any = {"defaultData":{"PurchaseLink":[{"link":"link 1","id":83},{"link":"link 2","id":56},{"link":"link 3","id":25},{"link":"link 4","id":5},{"link":"link 5","id":94}],"Videos":[{"videoLink":"videoLink 1","id":65},{"videoLink":"videoLink 2","id":41},{"videoLink":"videoLink 3","id":70},{"videoLink":"videoLink 4","id":15},{"videoLink":"videoLink 5","id":59}],"NFLStars":[{"imageLink":"imageLink 1","id":90},{"imageLink":"imageLink 2","id":26},{"imageLink":"imageLink 3","id":41},{"imageLink":"imageLink 4","id":53},{"imageLink":"imageLink 5","id":69}]}};
export default data;
