// Source code generated by AppGPT (www.appgpt.tech)

 
let data: any = {"defaultData":{"PurchaseLink":[{"link":"link 1","id":0},{"link":"link 2","id":48},{"link":"link 3","id":77},{"link":"link 4","id":39},{"link":"link 5","id":21}],"Videos":[{"videoLink":"videoLink 1","id":64},{"videoLink":"videoLink 2","id":54},{"videoLink":"videoLink 3","id":57},{"videoLink":"videoLink 4","id":46},{"videoLink":"videoLink 5","id":72}],"NFLStars":[{"imageLink":"imageLink 1","id":48},{"imageLink":"imageLink 2","id":75},{"imageLink":"imageLink 3","id":82},{"imageLink":"imageLink 4","id":95},{"imageLink":"imageLink 5","id":59}]}};
export default data;
