// Source code generated by AppGPT (www.appgpt.tech)

 
let data: any = {"defaultData":{"PurchaseLink":[{"link":"link 1","id":42},{"link":"link 2","id":65},{"link":"link 3","id":78},{"link":"link 4","id":66},{"link":"link 5","id":57}],"Videos":[{"videoLink":"videoLink 1","id":95},{"videoLink":"videoLink 2","id":36},{"videoLink":"videoLink 3","id":99},{"videoLink":"videoLink 4","id":17},{"videoLink":"videoLink 5","id":14}],"NFLStars":[{"imageLink":"imageLink 1","id":49},{"imageLink":"imageLink 2","id":35},{"imageLink":"imageLink 3","id":77},{"imageLink":"imageLink 4","id":0},{"imageLink":"imageLink 5","id":13}]}};
export default data;
